remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme 

title: "Kulinarische Weltreise"            
description: "Eine kulinarische Weltreise. Ein Gericht für jede Woche."
url: "https://jakobschumacher.github.io"     
baseurl: "/kulinarische-weltreise"         
lang: "de-DE"                              
author: "Jakob Schumacher"
github_username: "jakobschumacher"

favicon: favicon.png
logo: /logo.webp


# Add custom CSS
custom_css: /assets/styles.css



