project:
  type: website
  output-dir: docs

author: "Jakob Schumacher"
lang: "de-DE"
date: today
date-format: "D. MMMM YYYY"

  
website:
  title: "Kulinarische Weltreise"
  favicon: favicon.png
  description: "Eine kulinarische Weltreise. Ein Gericht für jede Woche."
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: Shakshuka
        href: shakshuka.qmd
      - text: Griechischer Salat mit gegrilltem Hähnchen
        href: griechischer-salat-mit-gegrilltem-haehnchen.qmd
      - text: Indisches Dal mit Reis
        href: indisches-dal-mit-reis.qmd
      - text: Tapas und Tortilla
        href: tapas.qmd
      - text: Bobotie
        href: bobotie.qmd
      - text: Marokkanischer Gemüsecouscous
        href: marokkanischer-gemuesecouscous.qmd
      - text: Hähnchen-Fajitas
        href: haehnchen-fajitas.qmd
      - text: Pad Thai mit Gemüse
        href: pad-thai-mit-gemuese.qmd
      - text: Sushi-Bowl
        href: sushi-bowl.qmd
      - text: Bibimbap
        href: bibimbap.qmd
      - text: Karibisches Jerk-Hähnchen mit Reis und Bohnen
        href: karibisches-jerk-haehnchen.qmd
      - text: Ratatouille
        href: ratatouille.qmd
      - text: Cevapcici mit Ajvar und Fladenbrot
        href: cevapcici.qmd
      - text: Süßkartoffel- und Kichererbsen-Curry
        href: suesskartoffel-kichererbsen-curry.qmd


format:
  html:
    theme:
      light: flatly 

